### ISSUE TITLE
Can't set argument `self` for security_group

### ISSUE THREAD

**Issue by palexvs** [coinbase/geoengineer#140]
\# GeoEngineer 0.1.4
\# Terraform v0.10.2
\# MacOs 10.12
\# ruby 2.3.0p0

I need to set attribute [self](https://www.terraform.io/docs/providers/aws/r/security_group.html#self) into `true` for `security_group`, but I can't because it's reserved word in Ruby.

These code returns `syntax error`:
```ruby
elb_sg = project.resource("aws_security_group", "SG") {
  name        "SG"
  description "SG"
  vpc_id      env.vpc_id

  ingress {
      from_port    22
      to_port      22
      protocol     "tcp"
      security_groups  ['1.1.1.1/32']
      self         true
  }

  tags { Name "SG" }
}
```

**Comment by palexvs** [comment]
I found a way how to do it: `assign_attribute('self', 'true')`

elb_sg = project.resource("aws_security_group", "SG") {
  name        "SG"
  description "SG"
  vpc_id      env.vpc_id

  ingress {
      from_port    22
      to_port      22
      protocol     "tcp"
      security_groups  ['1.1.1.1/32']
      assign_attribute('self', 'true')
  }

  tags { Name "SG" }
}

Maybe it would be good to add it in documentation to make more obvious 

Thank you

**Comment by grahamjenson** [comment]
@palexvs because `self` is a reserved word in ruby it cannot be used in the Geo DSL. However, `self` refers to the `ingress` (`SubResource`) object being defined. With your solution of using `assign_attribute('self', 'true')` you could also use the `[]` operator, e.g. `self["self"] = true` to define this attribute.
